#!/bin/bash
if [ ! -v EMACS ]
then
    . $HOME/.bash_profile
fi
while [ ! -f /tmp/stop-agenda-kiosk ]
do
    emacs -q -l $EMACS/special-setups/tasks/org-agenda-kiosk.el -f org-agenda-kiosk
    rm -f /tmp/restart-agenda-kiosk
done
rm -f /tmp/stop-agenda-kiosk
