#!/bin/bash
DIRECTORIES="$EHOME/common/* $EHOME/open-projects/* $EHOME/Dropbox/* $EHOME/library"
SERVER=whinberry
SERVERMOUNT=/nfs/whinberry
read -p "Password for $USER on $SERVER: " RSYNC_PASSWORD
export RSYNC_PASSWORD
for DIR in $DIRECTORIES
do
    REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
    echo Updating $DIR from $REMOTEDIR on $SERVER
    if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
    then
	rsync -uavC $SERVERMOUNT/$REMOTEDIR/ $DIR
    else
	rsync -uaCvz $USER@$SERVER:$SERVERMOUNT/$REMOTEDIR/ $DIR
    fi
done
