#!/bin/bash
DIRECTORIES="$EHOME/common/* $EHOME/open-projects/* $EHOME/Dropbox/* $EHOME/library"
SERVER=${1-whinberry}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem
# read -p "Password for $SERVERUSER on $SERVER: " RSYNC_PASSWORD
# export RSYNC_PASSWORD
for DIR in $DIRECTORIES
do
    REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
    echo Updating $DIR from $REMOTEDIR on $SERVER
    if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
    then
	rsync -uavC $SERVERMOUNT/$REMOTEDIR/ $DIR
    else
	rsync -uaCvz $SERVERUSER@$SERVER:$SERVERDIR/$REMOTEDIR/ $DIR
    fi
done
