#!/bin/bash
# grep jar
OPTS=""
while true
do
	case $1 in
	  -*)  OPTS="$OPTS $1"
	       shift ;;
	  *)   break ;;
	esac
done
PATTERN=$1
JAR=${2-/work/johstu01/build/trunk/work/src/arm.com/uniSched/build/libs/aggregator-1.0.jar}
jar tvf $JAR | grep $OPTS $PATTERN
