#!/bin/bash
SERVER=${1-$HOMESERVER}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem
DIR=$EHOME/Dropbox/org

REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
then
    echo Updating $DIR into $SERVERMOUNT/$REMOTEDIR on $SERVER via nfs
    rsync -uavC $DIR/ $SERVERMOUNT/$REMOTEDIR
else
    echo Updating $DIR into $SERVERUSER@$SERVER:$SERVERDIR/$REMOTEDIR on $SERVER via ssh
    rsync -uaCvz $DIR/ $SERVERUSER@$SERVER:$SERVERDIR/$REMOTEDIR
fi
