#!/bin/bash
SCRIPT_DIR=$(dirname $(readlink -f "$0"))

if [ ! -d $SCRIPT_DIR/packhack.env ]
then
    pushd $SCRIPT_DIR
    python3 -m venv packhack.env
    source $SCRIPT_DIR/packhack.env/bin/activate
    pip install pipreqs
    pip install tomlkit
    deactivate
    popd
fi

source $SCRIPT_DIR/packhack.env/bin/activate

$SCRIPT_DIR/packhack.py $*
