#!/bin/bash
echo Pomodoro started at $(date --iso-8601=minutes)
sleep ${POMODORO_SECS-1500}
POMODORO_LOG=${POMODORO_LOG-$HOME/.pomodoros}
GALLERY=/gallery/$USER/photos/Places
if [ ! -d $GALLERY ]
then
    GALLERY=$HOME/Pictures
fi
eom $(randimage $GALLERY) &
echo $(date --iso-8601=minutes) $* >> $POMODORO_LOG
SOUND=$(randimage $HOME/Music)
case $SOUND in
    *.ogg) ogg123 -K 30 $SOUND ;;
    *.mp3) mpg123 -N 30 $SOUND ;;
    *) ;;
esac
