#!/bin/bash
echo Pomodoro started at $(date --iso-8601=minutes)
sleep ${POMODORO-1500}
LOGFILE=$HOME/.pomodoros
GALLERY=/gallery/$USER/photos/Places
if [ ! -d $GALLERY ]
then
    GALLERY=$HOME/Pictures
fi
eom $(randimage $GALLERY) &
echo $(date --iso-8601=minutes) $* >> $LOGFILE
