#!/bin/bash

for GITDIR in $EMACS $CONFIG $SCRIPTS $OPEN_PROJECTS/wearables $OPEN_PROJECTS/elisp-cad $OPEN_PROJECTS/zorg-mode $OPEN_PROJECTS/cnc-things $OPEN_PROJECTS/natlangfun $OPEN_PROJECTS/mvphotos $OPEN_PROJECTS/ps-verse
do
    if [ -d $GITDIR ]
    then
	cd $GITDIR
	echo Pulling $GITDIR
	git pull
    else
	echo Skipping $GITDIR as it does not exist
    fi
done

$SCRIPTS/afterpull
