#!/bin/bash
DIRECTORIES="$EHOME/common/* $EHOME/Dropbox/* $EHOME/library"
SERVER=${1-$HOMESERVER}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem

echo Updating $HOME/common from $SERVERUSER@$SERVER:/mnt/usbmem/common/ on $SERVER via ssh on port $HOMESERVERSSHPORT
rsync -uaCvz -e "ssh -p $HOMESERVERSSHPORT" $SERVERUSER@$SERVER:/mnt/usbmem/common/ $HOME/common
