#!/bin/bash
DIRECTORIES="$EHOME/common/* $EHOME/Dropbox/* $EHOME/library"
SERVER=${1-$HOMESERVER}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem
# read -p "Password for $SERVERUSER on $SERVER: " RSYNC_PASSWORD
# export RSYNC_PASSWORD
for DIR in $DIRECTORIES
do
    REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
    if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
    then
	echo Updating $DIR from $SERVERMOUNT/$REMOTEDIR/ on $SERVER via nfs
	rsync -uavC $SERVERMOUNT/$REMOTEDIR/ $DIR
    else
	echo Updating $DIR from $SERVERUSER@$SERVER:/$SERVERDIR/$REMOTEDIR/ on $SERVER via ssh on port $HOMESERVERSSHPORT
	rsync -uaCvz -e "ssh -p $HOMESERVERSSHPORT" $SERVERUSER@$SERVER:/$SERVERDIR/$REMOTEDIR/ $DIR
    fi
done
