#!/bin/bash

ALL=false			# todo: flag for this
SUBCOMMAND=pull

while getopts ":ac:" opt; do
    case ${opt} in
        a) ALL=true
           ;;
        c) SUBCOMMAND=$OPTARG
           ;;
        \?) echo "Usage: pullrepos [-a] [-c gitcommand]"
            ;;
    esac
done
shift $((OPTIND -1))

# If my directory variables aren't defined, run my shell setup.  This
# is aimed for use from cron.
if [ -z $OPEN_PROJECTS ]
then
    . $HOME/.bashrc
fi

for GITDIR in $MY_PROJECTS/*
do
    pushd $GITDIR
    echo Pulling $GITDIR
    git $SUBCOMMAND
    popd
done

if $ALL
then
    for REPOFILE in $(find $OPEN_PROJECTS -name .git)
    do
	GITDIR=$(dirname $REPOFILE)
	pushd $GITDIR
	echo Pulling $GITDIR
	git $SUBCOMMAND
	popd
    done
fi

$SCRIPTS/afterpull
