#!/bin/bash

for GITDIR in $EMACS $ORGLISP $CONFIG $SCRIPTS $OPEN_PROJECTS/wearables $OPEN_PROJECTS/elisp-cad $OPEN_PROJECTS/zorg-mode $OPEN_PROJECTS/cnc-things $OPEN_PROJECTS/natlangfun $OPEN_PROJECTS/mvphotos $OPEN_PROJECTS/ps-verse $OPEN_PROJECTS/qs
do
    if [ -d $GITDIR ]
    then
	cd $GITDIR
	echo Pulling $GITDIR
	git pull
    else
	PROJECT=`basename $GITDIR`
	echo "Skipping $GITDIR (for project $PROJECT) as it does not exist"
	echo Try git clone https://github.com/hillwithsmallfields/$PROJECT.git
    fi
done

$SCRIPTS/afterpull
