#!/bin/bash

for GITDIR in $EMACS $CONFIG $SCRIPTS $OPEN_PROJECTS/wearables $OPEN_PROJECTS/elisp-cad $OPEN_PROJECTS/zorg-mode $OPEN_PROJECTS/cnc-things
do
  cd $GITDIR
  echo Pulling $GITDIR
  git pull
done

$SCRIPTS/afterpull
