#!/bin/bash
DIRECTORIES="$COMMON/org $VEHICLES/Marmalade $MYSELFORG $COMMON/notes"
SERVER=${1-$HOMESERVER}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem
# read -p "Password for $SERVERUSER on $SERVER: " RSYNC_PASSWORD
# export RSYNC_PASSWORD
for DIR in $DIRECTORIES
do
    if [ -d $DIR ]
    then
	REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
	if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
	then
	    echo Updating $DIR from $SERVERMOUNT/$REMOTEDIR/ on $SERVER via nfs
	    rsync -uavC $SERVERMOUNT/$REMOTEDIR/ $DIR
	else
	    echo Updating $DIR from $SERVERUSER@$SERVER:$HOMESERVERSSHPORT/$SERVERDIR/$REMOTEDIR/ on $SERVER via ssh
	    rsync -uaCvz $SERVERUSER@$SERVER:$HOMESERVERSSHPORT/$SERVERDIR/$REMOTEDIR/ $DIR
	fi
    fi
done
