#!/bin/bash
DIRECTORIES="$COMMON/org $VEHICLES/Marmalade $MYSELFORG $COMMON/notes"
SERVER=${1-$HOMESERVER}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem
# read -p "Password for $SERVERUSER on $SERVER: " RSYNC_PASSWORD
# export RSYNC_PASSWORD
for DIR in $DIRECTORIES
do
    if [ -d $DIR ]
    then
	REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
	if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
	then
	    echo Using: rsync -uavC $DIR/ $SERVERMOUNT/$REMOTEDIR
	    rsync -uavC $DIR/ $SERVERMOUNT/$REMOTEDIR
	else
	    echo Using: rsync -uaCvz -e "ssh -p $HOMESERVERSSHPORT" $DIR/ $SERVERUSER@$SERVER:/$SERVERDIR/$REMOTEDIR
	    rsync -uaCvz -e "ssh -p $HOMESERVERSSHPORT" $DIR/ $SERVERUSER@$SERVER:/$SERVERDIR/$REMOTEDIR
	fi
    fi
done
