#!/bin/bash
for GITDIR in $EMACS $ORGLISP $CONFIG $SCRIPTS $OPEN_PROJECTS/wearables $OPEN_PROJECTS/elisp-cad $OPEN_PROJECTS/zorg-mode $OPEN_PROJECTS/cnc-things $OPEN_PROJECTS/natlangfun $OPEN_PROJECTS/mvphotos $OPEN_PROJECTS/ps-verse $OPEN_PROJECTS/qs $OPEN_PROJECTS/textualosm $OPEN_PROJECTS/arduino-mode $OPEN_PROJECTS/ledger
do
  echo Pushing $GITDIR
  cd $GITDIR
  git push
done
