#!/bin/bash
DIRECTORIES="$COMMON/org $VEHICLES/Marmalade $MYSELFORG $COMMON/notes"
SERVER=${1-$HOMESERVER}
SERVERMOUNT=/nfs/whinberry
SERVERDIR=/mnt/usbmem
# read -p "Password for $SERVERUSER on $SERVER: " RSYNC_PASSWORD
# export RSYNC_PASSWORD
for DIR in $DIRECTORIES
do
    if [ -d $DIR ]
    then
	REMOTEDIR=`echo $DIR | sed s:$EHOME/::`
	if [ -d "$SERVERMOUNT/$REMOTEDIR" ]
	then
	    echo Updating $DIR into $SERVERMOUNT/$REMOTEDIR on $SERVER via nfs
	    rsync -uavC $DIR/ $SERVERMOUNT/$REMOTEDIR
	else
	    echo Updating $DIR into $SERVERUSER@$SERVER:$HOMESERVERSSHPORT/$SERVERDIR/$REMOTEDIR on $SERVER via ssh
	    rsync -uaCvz $fDIR/ $SERVERUSER@$SERVER:$HOMESERVERSSHPORT/$SERVERDIR/$REMOTEDIR
	fi
    fi
done
