#!/bin/bash
EFHOME=${EHOME-/mnt/usbmem}
EFORG=$EFHOME/common/org
EFMYSELFORG=$EFHOME/myself/org
SNAPSHOTS=$EFHOME/org-snapshots
DATE=`date "+%Y-%m-%d"`
mkdir -p $SNAPSHOTS
tar czf $SNAPSHOTS/$DATE.tgz $EFORG $EFMYSELFORG
