#!/bin/bash

if [ -x /usr/local/bin/emacs ]
then
    EMACSBIN=/usr/local/bin/emacs
else
    EMACSBIN=emacs
fi
echo Using $EMACSBIN as emacs

$EMACSBIN -q -l $EMACS/special-setups/tasks/tasks-emacs-setup.el $*
