#!/bin/bash
if [ `hostname` == whinberry ]
then
    if [ -x /usr/local/bin/emacs ]
    then
	EMACSBIN=/usr/local/bin/emacs
    else
	EMACSBIN=emacs
    fi
    echo Using $EMACSBIN as emacs
    $EMACSBIN -q -l $EMACS/special-setups/tasks/tasks-web-update.el --batch
else
    echo Pushing org files to server
    pushorg
    echo Telling server to update web pages
    ssh $SERVERUSER@$HOMESERVER /mnt/usbmem/JCGS-scripts/tasks-web-update
fi
