#! /bin/sh
purge $COMMON/emacs
cd $COMMON/emacs
TAZ=$COMMON/www/computing/emacs/lisp/lisp.taz
tar cvfz $TAZ *
cd $HOME
echo Copying to server
tocb1 $TAZ
rm $TAZ
echo Logging in to server to run wwwunpack
ssh -l john.cb1.com www.cb1.com bin/wwwunpack
