#!/bin/bash

PHONE=${1-/mnt/phone-mmc}

PARTITION_SETUP=false
UNMOUNT=false

while true
do
    case $PHONE in
	-p)       PARTITION_SETUP=true
	          shift ;;
	/mnt/*)   break ;;
	/media/*) break ;;
	/dev/*)   if $PARTITION_SETUP
		  then
		      sudo parted $PHONE print
		  fi
		  sudo mount -o rw,uid=$USER $PHONE /mnt/phone-mmc
		  PHONE=/mnt/phone-mmc
		  UNMOUNT=true
		  break ;;
    esac
done

COMMON=$HOME/common
PRIVATE=/mnt/crypted

cp -rupv $HOME/finances $PHONE
# rsync -av $COMMON/
cp -upv $VEHICLES/Marmalade/*.org $VEHICLES/Marmalade/*.gnumeric $PHONE/common/vehicles/Marmalade/
cp -upv $DROPBOX/Categorical_Imperative/*.org $DROPBOX/Categorical_Imperative/*.gnumeric $PHONE/common/Categorical_Imperative
cp -upv $DROPBOX/org/diary $PHONE/common/org/diary
cp -upv $ORG/*.org $PHONE/common/org
cp -upv $DROPBOX/languages/languages.deck $PHONE/common/languages
cp -upv $DROPBOX/health/*.gnumeric $PHONE/common/health/
if [ -d $PRIVATE/personal/journal ]
then
  cp -upv $PRIVATE/personal/journal/dates/for-diary $PHONE/common/tmp/for-diary
fi

if $UNMOUNT
then
    sudo umount $PHONE
fi
