#!/bin/bash

CONFIG_DIR=$MY_PROJECTS/JCGS-config
TARGET=/etc/motion

source $HOME/.bashrc_local

cd $CONFIG_DIR
git pull

sudo envsubst < $CONFIG_DIR/motion/motion.conf > $TARGET/motion.conf
sudo envsubst < $CONFIG_DIR/motion/camera1.conf > $TARGET/camera1.conf

